version: "3.9"

networks:
    laravel:
        name: laravel

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        depends_on:
            - php
            # - mysql
            - postgres
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

#    apache:
#        build:
#            context: .
#            dockerfile: apache.dockerfile
#        container_name: apache
#        ports:
#            - 80:80
#            - 443:443
#        volumes:
#            - ./src:/var/www/html
#        networks:
#            - virtual-fair
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    postgres:
        image: postgres:15
        platform: linux/amd64
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - ./postgresql:/var/lib/postgresql/data
            - ./pginit:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin123
        networks:
            - laravel

    # mysql:
    #     image: mysql:8.0.27
    #     platform: linux/amd64
    #     container_name: mysql
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./mysql:/var/lib/mysql
    #     environment:
    #         MYSQL_DATABASE: laraveldb
    #         MYSQL_USER: laravel
    #         MYSQL_PASSWORD: laravel
    #         MYSQL_ROOT_PASSWORD: secret
    #     networks:
    #         - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['php', 'artisan']
        networks:
            - laravel

    npm:
        image: node:current-alpine
        container_name: npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel

    dbadmin:
        # depends_on:
        #     - postgres
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@example.com
            - PGADMIN_DEFAULT_PASSWORD=admin123
        volumes:
            - ./pgadmin:/var/lib/pgadmin
            # - ./pgadmin:/pgadmin4/
        ports:
            - "5050:80"
        networks:
            - laravel







